rav_partner_scope:
    resource: "@RavPartnerScopeBundle/Resources/config/routing.yml"
    prefix:   /

rav_service:
    resource: "@RavServiceBundle/Resources/config/routing.yml"
    prefix:   /

rav_some:
    resource: "@RavSomeBundle/Resources/config/routing.yml"
    prefix:   /

