rav_service:
    resource: "@RavServiceBundle/Resources/config/routing.yml"
    prefix:   /

rav_some:
    resource: "@RavSomeBundle/Resources/config/routing.yml"
    prefix:   /

rav_block:
    resource: "@RavBlockBundle/Resources/config/routing.yml"
    prefix:   /block/